import type { SlurpSettings } from "../settings/slp-settings-contract";
import type { SlpBackstageSection, SlpBackstageTarget } from "../../base/navigation/slp-backstage-target";

export type SlpBackstageScope = "all-slurp" | "this-viewer" | "new-creators" | "creator";
export type SlpBackstagePlacement = {
  section: SlpBackstageSection;
  target: SlpBackstageTarget;
  scope: SlpBackstageScope;
  searchTerms: readonly string[];
  /** Runtime or setup state with no Backstage control; hidden from search and exempt from anchors. */
  internal?: true;
};

const place = (
  section: SlpBackstageSection,
  target: SlpBackstageTarget,
  scope: SlpBackstageScope,
  ...searchTerms: string[]
): SlpBackstagePlacement => ({ section, target, scope, searchTerms });
const world = (target: SlpBackstageTarget, ...terms: string[]) => place("world", target, "all-slurp", ...terms);
const automation = (target: SlpBackstageTarget, ...terms: string[]) =>
  place("automation", target, "all-slurp", ...terms);
const internal = (placement: SlpBackstagePlacement): SlpBackstagePlacement => ({ ...placement, internal: true });
const prompts = (...terms: string[]) => place("prompts", "prompts", "all-slurp", ...terms);
const maintenance = (...terms: string[]) => place("maintenance", "autopurge", "all-slurp", ...terms);

/** One searchable, canonical Backstage home for every persisted setting. */
export const SLP_BACKSTAGE_SETTING_PLACEMENT: Record<keyof SlurpSettings, SlpBackstagePlacement> = {
  inlineAdsEnabled: world("ads", "ads", "promotions", "feed"),
  inlineAdsFrequency: world("ads", "ad frequency", "promotions"),
  inlineAdsSteering: world("ads", "personalized ads", "random ads"),
  inlineAdsPreferredTags: world("ads", "ad tags", "interests"),
  inlineAdsContentCeiling: world("ads", "ad rating", "content ceiling"),
  inlineAdsTone: world("ads", "ad voice", "tone"),
  inlineAdsEra: world("ads", "ad era", "style"),
  inlineAdsWorldContext: world("ads", "ad world", "context"),
  inlineAdsImagesEnabled: world("ads", "ad images", "pictures"),
  inlineAdsImageConnectionId: world("ads", "ad image connection", "image model"),
  inlineAdsLorebookId: world("ads", "ad lorebook"),
  inlineAdsLorebookRevision: internal(world("ads", "ad lorebook revision")),
  walletEnabled: world("wallet", "coins", "wallet", "economy"),
  walletUnlockCost: world("wallet", "post price", "unlock cost"),
  walletSubscriptionCost: world("wallet", "subscription price"),
  pricingDynamicCharacters: world("wallet", "dynamic pricing"),
  pricingMaxWeeklyChangePercent: world("wallet", "weekly price change"),
  walletStipendFloor: world("wallet", "stipend", "balance floor"),
  walletDayStartHour: world("wallet", "wallet day", "reset hour"),
  walletAdReward: world("wallet", "ad reward"),
  walletAdDailyCap: world("wallet", "daily ad cap"),
  walletEngagementReward: world("wallet", "engagement reward"),
  walletEngagementDailyCap: world("wallet", "engagement cap"),
  walletCreatorRevenueSharePercent: world("wallet", "creator revenue share"),
  imageWidth: automation("images", "post image width", "resolution"),
  imageHeight: automation("images", "post image height", "resolution"),
  storyRate: automation("general", "story posts", "story rate"),
  storyImagesEnabled: automation("images", "story posts", "image stories"),
  storyLifetimeHours: automation("images", "story lifetime", "moments"),
  teaserRate: world("wallet", "teaser", "free posts", "fish for subscribers"),
  projectRate: world("arcs", "projects", "project rate"),
  arcPace: world("arcs", "arc pace", "story speed"),
  arcAffectsMood: world("arcs", "arc mood"),
  arcFanReactions: world("arcs", "arc fan reactions"),
  arcAutoMode: world("arcs", "automatic arcs", "story suggestions"),
  arcCooldownWeeks: world("arcs", "arc cooldown"),
  arcSource: world("arcs", "arc source", "generated stories"),
  arcMaxConcurrentAuto: world("arcs", "concurrent arcs"),
  arcDirectorMode: world("arcs", "arc director"),
  arcPollHours: world("arcs", "arc polling"),
  arcStatEffects: world("arcs", "arc stat effects"),
  arcCrossovers: world("arcs", "arc crossovers"),
  arcLibrary: world("arcs", "arc library", "stories"),
  discoveryTags: world("tags", "tags", "discovery", "categories"),
  storyImageWidth: automation("images", "story image width", "resolution"),
  storyImageHeight: automation("images", "story image height", "resolution"),
  refreshesPerDay: internal(automation("general", "refreshes per day", "generation")),
  generationGuidance: prompts("writing guidance", "spice", "tone"),
  audienceTone: world("audience", "audience tone", "comments"),
  worldActivity: world("audience", "world activity", "crowd activity"),
  platformScale: world("audience", "platform scale", "audience size"),
  postsPerDay: automation("general", "posts per day", "publishing pace"),
  autoPostingScheduleEnabled: automation("general", "automatic publishing", "schedule"),
  autoPostGenerationMode: automation("general", "prepare posts", "on demand"),
  fanActivityEnabled: world("audience", "fan activity", "background audience"),
  generationConnectionId: automation("general", "text connection", "model"),
  imageContextMode: automation("images", "image context", "vision"),
  imageContextConnectionId: automation("images", "vision connection", "image description"),
  imageGenerationConnectionId: internal(automation("images", "image connection", "image model")),
  imageGenerationPrompt: prompts("image instructions", "image prompt"),
  imagePromptInterpretation: prompts("image prompt interpretation", "image prompt style", "Danbooru"),
  enableImageInterpretation: prompts("interpret image prompts"),
  imageGenerationUseAvatarReferences: automation("images", "avatar references"),
  imageGenerationIncludeDescriptions: automation("images", "image descriptions"),
  autoPostingImagesEnabled: automation("images", "automatic post images"),
  allowRandomUsers: world("audience", "random users", "ambient fans"),
  allowProfessorMari: internal(automation("general", "Professor Mari", "participants")),
  participantSelectionMode: internal(automation("general", "participants", "creator selection")),
  participantMin: internal(automation("general", "minimum participants")),
  participantMax: internal(automation("general", "maximum participants")),
  invitedCharacterGroupIds: internal(place("creators", "creators", "new-creators", "invited groups", "creator groups")),
  audienceCharacters: world("audience", "audience characters", "invited characters", "characters as fans"),
  audienceCharacterGroupIds: world("audience", "audience character groups", "invited character groups"),
  audienceCharacterLimit: world("audience", "audience character limit", "invited character limit"),
  carryoverModes: automation("general", "carryover", "Engine chats"),
  carryoverHours: automation("general", "carryover hours"),
  carryoverMaxItems: automation("general", "carryover limit"),
  postMaxLength: automation("general", "post length", "maximum post length"),
  postShowMoreLength: automation("general", "show more", "post preview length"),
  characterImageInstructions: place("creators", "creators", "creator", "character image instructions"),
  creatorCollabs: place("creators", "creators", "creator", "collabs", "collab partners", "crossover"),
  promptPresets: prompts("prompt presets", "writing presets"),
  promptBlocks: prompts("prompt block builder", "prompt order", "prompt blocks"),
  professorMariCreatorSource: automation("general", "Professor Mari creator", "new creators"),
  enableEnhancedTimelineWriting: internal(automation("general", "enhanced timeline writing")),
  includeCharacterSchedules: internal(automation("general", "character schedules")),
  enableLorebookContext: prompts("lorebook context"),
  enableImagePrompts: internal(automation("images", "image prompts")),
  maxImagesPerRefresh: internal(automation("images", "images per refresh")),
  maxGeneratedPostsPerRefresh: internal(automation("general", "posts per refresh")),
  maxLikesPerRefresh: internal(automation("general", "likes per refresh")),
  maxRepliesPerRefresh: internal(automation("general", "replies per refresh")),
  allowGalleryImageAttachments: automation("images", "gallery attachments"),
  fanActivityRunsPerDay: world("audience", "audience runs per day"),
  audienceReactionBank: world("audience", "reaction bank", "fan replies"),
  fanLikesPerRefresh: world("audience", "fan likes per refresh"),
  fanRepliesPerRefresh: world("audience", "fan replies per refresh"),
  fanArchetypeWeights: world("audience", "fan type weights", "audience mix"),
  fanTypes: world("audience", "fan types", "audience personas"),
  platformEvents: world("events", "events", "holidays", "christmas", "halloween", "special dates"),
  messagesAwayRepliesEnabled: world("messaging", "away replies", "automatic messages"),
  messagesReplyBubbleLimit: world("messaging", "reply bubbles", "message length"),
  messagesDefaultDmPolicy: world("messaging", "DM policy", "message access"),
  messagesDefaultRequestFee: world("messaging", "message request fee"),
  messagesDefaultPpvPrice: world("messaging", "message image price", "PPV"),
  messagesUnscheduledAlwaysReachable: world("messaging", "always reachable", "message schedule"),
  messagesHighRapportDelayMinMinutes: world("messaging", "close fan reply minimum"),
  messagesHighRapportDelayMaxMinutes: world("messaging", "close fan reply maximum"),
  messagesMediumRapportDelayMinMinutes: world("messaging", "regular fan reply minimum"),
  messagesMediumRapportDelayMaxMinutes: world("messaging", "regular fan reply maximum"),
  messagesUnknownReturnDelayMinutes: world("messaging", "unknown return delay"),
  messagesMaxReplyDelayMinutes: world("messaging", "maximum reply delay"),
  messagesRecentPostAwayMinMinutes: world("messaging", "recent post away minimum"),
  messagesRecentPostAwayMaxMinutes: world("messaging", "recent post away maximum"),
  messagesStalePostAwayMinMinutes: world("messaging", "stale post away minimum"),
  messagesStalePostAwayMaxMinutes: world("messaging", "stale post away maximum"),
  autopurgeEnabled: maintenance("automatic cleanup", "autopurge"),
  autopurgeRetentionValue: maintenance("retention", "keep media"),
  autopurgeRetentionUnit: maintenance("retention unit"),
  autopurgeKeepPosts: maintenance("keep posts", "media only"),
  autopurgeIncludeMessageMedia: maintenance("message media cleanup"),
  autopurgeNextRunAt: maintenance("next cleanup"),
  nightQuiet: automation("general", "quiet hours", "night"),
  simulationTuning: world("audience", "simulation tuning", "fine tune audience"),
  modelBudget: world("audience", "AI budget", "model calls"),
  onboarding: internal(place("creators", "creators", "new-creators", "setup", "onboarding")),
};
