import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { slurpImageExtension } from "../packages/slurp2/src/engine/packages/server/src/services/slurp/slurp-image-format";

// Uploaded media is magic-byte verified. Generated bytes were not: they went to disk under
// whatever extension the provider claimed, so a mislabelled response was stored and served under
// a filename that did not match its contents.

const b64 = (bytes: number[]) => Buffer.from(bytes).toString("base64");

const png = b64([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a, 0, 0, 0, 0]);
const jpg = b64([0xff, 0xd8, 0xff, 0xe0, 0, 0, 0, 0, 0, 0, 0, 0]);
const gif = b64([0x47, 0x49, 0x46, 0x38, 0x39, 0x61, 0, 0, 0, 0, 0, 0]);
const bmp = b64([0x42, 0x4d, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]);
const webp = b64([0x52, 0x49, 0x46, 0x46, 0, 0, 0, 0, 0x57, 0x45, 0x42, 0x50]);

// The bytes win over a wrong declared extension.
assert.equal(slurpImageExtension(png, "jpg"), "png");
assert.equal(slurpImageExtension(jpg, "png"), "jpg");
assert.equal(slurpImageExtension(gif, "webp"), "gif");
assert.equal(slurpImageExtension(bmp, "png"), "bmp");
assert.equal(slurpImageExtension(webp, "png"), "webp");

// Unrecognised bytes fall back to the declared extension, normalised.
assert.equal(slurpImageExtension(b64([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]), "jpeg"), "jpg");
assert.equal(slurpImageExtension(b64([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]), ".WEBP"), "webp");
// An unknown or hostile fallback never becomes the filename.
assert.equal(slurpImageExtension(b64([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]), "svg"), "png");
assert.equal(slurpImageExtension(b64([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]), "../../evil"), "png");

// The generated-image path must actually use it.
const images = readFileSync(
  "packages/slurp2/src/engine/packages/server/src/services/slurp/slurp-images.service.ts",
  "utf8",
);
assert.match(images, /slurpImageExtension\(image\.base64, image\.ext\)/u, "staged bytes must be sniffed");

console.log("slurp image format regression passed");
