import { useEffect, useState, type CSSProperties } from "react";
import { createRoot, type Root } from "react-dom/client";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import i18next from "i18next";
import { I18nextProvider, initReactI18next } from "react-i18next";
import { Toaster } from "sonner";
import german from "./localization/locales/de.json";
import english from "./localization/locales/en.json";
import korean from "./localization/locales/ko.json";
import polish from "./localization/locales/pl.json";
import { AppDialogRenderer } from "./components/ui/AppDialogRenderer";
import { ModalPortalContext } from "./components/ui/Modal";
import { NoodleView } from "./components/noodle/NoodleView";
import { NoodleLatestPostsWidget } from "./components/noodle/NoodleLatestPostsWidget";
import { configureNoodlePackageState } from "./stores/noodle-package.store";

const client = new QueryClient({
  defaultOptions: { queries: { retry: false } },
});
const localization = i18next.createInstance();
void localization.use(initReactI18next).init({
  fallbackLng: "en",
  interpolation: { escapeValue: false },
  lng: "en",
  resources: {
    de: { translation: german },
    en: { translation: english },
    ko: { translation: korean },
    pl: { translation: polish },
  },
});

type CapabilityElement = HTMLElement & {
  capabilityProps?: Record<string, unknown>;
  __root?: Root | null;
};

const NOODLE_ELEMENT_TAG = "marinara-capability-noodle";
const NOODLE_STYLE_ID = "marinara-capability-noodle-styles";
let noodlePackageStyles = "";

function syncNoodlePackageStyles() {
  const existing = document.getElementById(NOODLE_STYLE_ID);
  if (!document.querySelector(NOODLE_ELEMENT_TAG) || !noodlePackageStyles) {
    existing?.remove();
    return;
  }
  const style = existing ?? document.createElement("style");
  style.id = NOODLE_STYLE_ID;
  style.textContent = noodlePackageStyles;
  if (!existing) document.head.appendChild(style);
}

/** Supplies the package-scoped stylesheet generated by the catalog build. */
export function setNoodlePackageStyles(styleText: string) {
  noodlePackageStyles = styleText;
  syncNoodlePackageStyles();
}

function NoodlePackageRoot({ element }: { element: CapabilityElement }) {
  const [revision, redraw] = useState(0);
  const props = element.capabilityProps ?? {};
  useEffect(() => {
    const update = () => redraw((value) => value + 1);
    element.addEventListener("marinara-capability-props", update);
    return () => element.removeEventListener("marinara-capability-props", update);
  }, [element]);
  useEffect(() => {
    configureNoodlePackageState(props);
    const localizationContext = props.localization;
    const requestedLocale =
      localizationContext && typeof localizationContext === "object" && !Array.isArray(localizationContext)
        ? (localizationContext as Record<string, unknown>).locale
        : null;
    const language = typeof requestedLocale === "string" ? requestedLocale.split("-")[0] : "en";
    const supportedLanguages = new Set(Object.keys(localization.options.resources ?? {}));
    void localization.changeLanguage(language && supportedLanguages.has(language) ? language : "en");
  }, [element, revision]);
  return (
    <I18nextProvider i18n={localization}>
      <QueryClientProvider client={client}>
        <ModalPortalContext.Provider value={element}>
          <div
            className="h-full min-h-0 overflow-hidden bg-[var(--background)] text-[var(--foreground)]"
            style={
              {
                "--noodle-accent": "#7EA7FF",
                "--noodle-divider": "color-mix(in srgb, #7EA7FF 28%, var(--border))",
                "--noodle-accent-foreground": "#071226",
              } as CSSProperties
            }
          >
            {element.getAttribute("view") === "widget" ? (
              props.widgetId === "latest-posts" || props.widgetId === "latest-posts-compact" ? (
                <NoodleLatestPostsWidget
                  active={props.active === true}
                  widgetLabel={typeof props.widgetLabel === "string" ? props.widgetLabel : undefined}
                  widgetDescription={typeof props.widgetDescription === "string" ? props.widgetDescription : undefined}
                  widgetAccent={typeof props.widgetAccent === "string" ? props.widgetAccent : undefined}
                  packageId={typeof props.packageId === "string" ? props.packageId : undefined}
                  packageVersion={typeof props.packageVersion === "string" ? props.packageVersion : null}
                  compact={props.widgetId === "latest-posts-compact"}
                  onOpenPost={
                    typeof props.onOpenPost === "function" ? (props.onOpenPost as (postId: string) => void) : undefined
                  }
                  onOpenNoodle={
                    typeof props.onOpenNoodle === "function" ? (props.onOpenNoodle as () => void) : undefined
                  }
                />
              ) : null
            ) : (
              <NoodleView
                focusPostId={typeof props.focusPostId === "string" ? props.focusPostId : null}
                onFocusPostHandled={
                  typeof props.onFocusPostHandled === "function" ? (props.onFocusPostHandled as () => void) : undefined
                }
              />
            )}
            {/* The package bundles its own copy of the dialog store, so the host's
                renderer never sees a dialog opened in here: showConfirmDialog would
                resolve nothing and every confirmed action stopped silently. Render
                the dialogs inside the package tree that opens them. */}
            {element.getAttribute("view") !== "widget" && <AppDialogRenderer />}
            {element.getAttribute("view") !== "widget" && <Toaster richColors />}
          </div>
        </ModalPortalContext.Provider>
      </QueryClientProvider>
    </I18nextProvider>
  );
}

class MarinaraNoodleElement extends HTMLElement {
  declare __root: Root | null;

  connectedCallback() {
    syncNoodlePackageStyles();
    this.__root ??= createRoot(this);
    this.__root.render(<NoodlePackageRoot element={this} />);
  }

  disconnectedCallback() {
    queueMicrotask(() => {
      if (!this.isConnected && this.__root) {
        this.__root.unmount();
        this.__root = null;
      }
      syncNoodlePackageStyles();
    });
  }
}

if (!customElements.get(NOODLE_ELEMENT_TAG)) {
  customElements.define(NOODLE_ELEMENT_TAG, MarinaraNoodleElement);
}
