import { Component, useEffect, useState, type ErrorInfo, type ReactNode } from "react";
import { createRoot, type Root } from "react-dom/client";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import i18next from "i18next";
import { Toaster } from "sonner";
import { I18nextProvider, initReactI18next } from "react-i18next";
import english from "./localization/locales/en.json";
import german from "./localization/locales/de.json";
import korean from "./localization/locales/ko.json";
import polish from "./localization/locales/pl.json";
import { SlurpHome } from "./components/slurp/SlurpHome";
import { ApiError } from "./lib/api-client";
import { useSlurpUIStore } from "./stores/slurp-package.store";
import { configureSlurpPackageState } from "./stores/slurp-package.store";
import { ModalPortalContext } from "./components/ui/Modal";
import { AppDialogRenderer } from "./components/ui/AppDialogRenderer";

const SLURP_ELEMENT_TAG = "marinara-capability-slurp2";
const SLURP_STYLE_ID = "marinara-capability-slurp2-styles";
// An Engine restart drops every request for a few seconds. With no retry, one poll landing in that
// window left the Hub on "Slurp could not be loaded." Network failures and 5xx retry with backoff
// (about 30s in total); a 4xx is a real answer and fails at once.
const client = new QueryClient({
  defaultOptions: {
    queries: {
      retry: (failures, error) => failures < 5 && !(error instanceof ApiError && error.status < 500),
    },
  },
});
const localization = i18next.createInstance();

void localization.use(initReactI18next).init({
  fallbackLng: "en",
  interpolation: { escapeValue: false },
  lng: "en",
  resources: {
    de: { translation: german },
    en: { translation: english },
    ko: { translation: korean },
    pl: { translation: polish },
  },
});

type CapabilityElement = HTMLElement & {
  capabilityProps?: Record<string, unknown>;
  __root?: Root | null;
  __portal?: HTMLDivElement | null;
};

let slurpPackageStyles = "";

/**
 * With accent animation on, the Engine repaints every `svg` inside a chrome token scope to the
 * chrome accent colour. Slurp's shell is such a scope, so an icon on an accent-filled button was
 * painted accent-on-accent and vanished, leaving the gap its label was spaced for. Icons here
 * follow their own button's text colour instead.
 */
const SLURP_ICON_COLOR_FIX =
  "[data-marinara-accent-animation] .mari-chrome-token-scope svg:not(.mari-rgb-static-icon){color:inherit;stroke:currentColor;}";

function syncSlurpPackageStyles() {
  const existing = document.getElementById(SLURP_STYLE_ID);
  if (!document.querySelector(SLURP_ELEMENT_TAG) || !slurpPackageStyles) {
    existing?.remove();
    return;
  }

  const style = existing ?? document.createElement("style");
  style.id = SLURP_STYLE_ID;
  style.textContent = `${slurpPackageStyles}\n${SLURP_ICON_COLOR_FIX}`;
  if (!existing) document.head.appendChild(style);
}

/** Supplies the package-scoped stylesheet generated by the catalog build. */
export function setSlurpPackageStyles(styleText: string) {
  slurpPackageStyles = styleText;
  syncSlurpPackageStyles();
}

function requestedLanguage(element: CapabilityElement) {
  const localizationContext = element.capabilityProps?.localization;
  if (!localizationContext || typeof localizationContext !== "object" || Array.isArray(localizationContext)) {
    return "en";
  }

  const locale = (localizationContext as Record<string, unknown>).locale;
  return typeof locale === "string" ? locale.split("-")[0] : "en";
}

/**
 * Without this, any render throw tears down the whole React root and leaves an empty panel next to
 * the Engine chrome, with nothing in the bug report to explain it.
 */
class SlurpErrorBoundary extends Component<{ children: ReactNode }, { error: Error | null }> {
  state: { error: Error | null } = { error: null };

  static getDerivedStateFromError(error: Error) {
    return { error };
  }

  componentDidCatch(error: Error, info: ErrorInfo) {
    console.error("[slurp2] render failed", error, info.componentStack);
  }

  render() {
    const { error } = this.state;
    if (!error) return this.props.children;
    return (
      <div className="flex h-full flex-col items-center justify-center gap-3 p-6 text-center text-sm">
        <p className="text-base font-semibold">{localization.t("ui.slurp.crash.title")}</p>
        <p className="text-[var(--muted-foreground)]">{localization.t("ui.slurp.crash.body")}</p>
        <pre className="max-w-full overflow-auto whitespace-pre-wrap text-xs text-[var(--muted-foreground)]">
          {error.message}
        </pre>
        <button
          type="button"
          onClick={() => this.setState({ error: null })}
          className="inline-flex min-h-10 items-center rounded-lg border border-[var(--noodle-accent)]/40 px-3 font-semibold text-[var(--noodle-accent)]"
        >
          {localization.t("capabilities.actions.tryAgain")}
        </button>
      </div>
    );
  }
}

function SlurpPackageRoot({ element }: { element: CapabilityElement }) {
  const [revision, redraw] = useState(0);
  const navigation = useSlurpUIStore((state) => state.navigation);
  const setNavigation = useSlurpUIStore((state) => state.setNavigation);
  const close = element.capabilityProps?.onClose;
  const onLeave = typeof close === "function" ? () => close() : undefined;

  useEffect(() => {
    // The host re-dispatches this event whenever capabilityProps change, so the store has to be
    // reconfigured as well. Redrawing alone left debugMode and reviewImagePromptsBeforeSend stuck
    // on their mount-time values until the tab was remounted.
    const update = () => {
      configureSlurpPackageState(element.capabilityProps ?? {});
      redraw((value) => value + 1);
    };
    configureSlurpPackageState(element.capabilityProps ?? {});
    element.addEventListener("marinara-capability-props", update);
    return () => element.removeEventListener("marinara-capability-props", update);
  }, [element]);

  useEffect(() => {
    const language = requestedLanguage(element);
    const supportedLanguages = new Set(Object.keys(localization.options.resources ?? {}));
    void localization.changeLanguage(supportedLanguages.has(language) ? language : "en");
  }, [element, revision]);

  return (
    <I18nextProvider i18n={localization}>
      <QueryClientProvider client={client}>
        <ModalPortalContext.Provider value={element.__portal ?? element}>
          <div className="h-full min-h-0 overflow-hidden bg-[var(--background)] text-[var(--foreground)]">
            <SlurpErrorBoundary>
              <SlurpHome navigation={navigation} onNavigate={setNavigation} onLeave={onLeave} />
              <AppDialogRenderer />
              <Toaster richColors />
            </SlurpErrorBoundary>
          </div>
        </ModalPortalContext.Provider>
      </QueryClientProvider>
    </I18nextProvider>
  );
}

class MarinaraSlurpElement extends HTMLElement {
  declare __root: Root | null;
  declare __portal: HTMLDivElement | null;

  connectedCallback() {
    syncSlurpPackageStyles();
    if (!this.__portal) {
      this.__portal = document.createElement("div");
      this.__portal.dataset.marinaraCapabilityScope = "slurp2";
      this.__portal.classList.add("mari-chrome-token-scope", "noodle-icon-scope");
      Object.assign(this.__portal.style, {
        inset: "0",
        pointerEvents: "none",
        position: "fixed",
        zIndex: "2147483000",
      });
      this.__portal.style.setProperty("--accent", "rgba(255, 126, 193, 0.14)");
      this.__portal.style.setProperty("--background", "#17121b");
      this.__portal.style.setProperty("--border", "rgba(255, 255, 255, 0.18)");
      this.__portal.style.setProperty("--foreground", "#fff7fc");
      this.__portal.style.setProperty("--muted-foreground", "#d8c9d4");
      this.__portal.style.setProperty("--noodle-accent", "#ff7ec1");
      this.__portal.style.setProperty("--noodle-accent-foreground", "#17121b");
      document.body.appendChild(this.__portal);
    }
    this.__root ??= createRoot(this);
    this.__root.render(<SlurpPackageRoot element={this} />);
  }

  disconnectedCallback() {
    queueMicrotask(() => {
      if (!this.isConnected && this.__root) {
        this.__root.unmount();
        this.__root = null;
      }
      if (!this.isConnected && this.__portal) {
        this.__portal.remove();
        this.__portal = null;
      }
      syncSlurpPackageStyles();
    });
  }
}

if (!customElements.get(SLURP_ELEMENT_TAG)) {
  customElements.define(SLURP_ELEMENT_TAG, MarinaraSlurpElement);
}
